services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ../confs/nginx_2.conf:/etc/nginx/conf.d/default.conf:ro
      - ../src/back/core:/var/www/spheer/core
      - ../src/front:/var/www/spheer/front
      - ../src/back/auth:/var/www/spheer/auth
    restart: always
    depends_on:
      - mysql
      - core

  core:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ../src/back/core:/var/www/spheer/core
      - ../confs/php.ini:/usr/local/etc/php/php.ini
    container_name: app_core
    networks:
      - back_front
      - default

  vue:
    build:
      context: ./dockerfiles
      dockerfile: vue.dockerfile
    volumes:
      - ../src/front:/var/www/spheer/front
    command: npm run build
    container_name: app_front
    networks:
      - back_front
      - default

  mysql:
    image: mysql:8.2
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ../envs/mysql.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:

networks:
  back_front:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450